apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-pizza-cheeser.fullname" . }}
  labels:
    {{- include "backend-pizza-cheeser.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend-pizza-cheeser.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend-pizza-cheeser.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HOST
              value: "pizza-cheeser-master"
            - name: ES_PIZZERIAS_ID
              value: "pizzerias"
            - name: ES_PORT
              value: "9200"
            - name: ES_LOCATION_ID
              value: "locations"
            - name: DEBUG_METRICS
              value: "true"
            - name: DEBUG
              value: "false"
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
