apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "backend-pizza-cheeser.fullname" . }}-migration
  labels:
    {{- include "backend-pizza-cheeser.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": keep
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "db/migrate.py"]
          env:
            {{- include "backend-pizza-cheeser.env_vars" . | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: "/opt/bin/backend/src/configuration"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "backend-pizza-cheeser.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
