apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-pizza-cheeser.fullname" . }}
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
  labels:
    {{- include "backend-pizza-cheeser.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "backend-pizza-cheeser.selectorLabels" . | nindent 4 }}
